### ISSUE TITLE
 Can't download reshaping model pytorch_model.pt

### ISSUE THREAD

**Issue by enesdikmen** [JianqiangRen/FlowBasedBodyReshaping#5]
Hi. I have tried to download the model file using the link provided in readme. The link opens up a page in chinese and I couldn't figure out a way to change the languge nor find the download button if there is any.

Can you help me please?

**Comment by JianqiangRen** [comment]
> Hi. I have tried to download the model file using the link provided in readme. The link opens up a page in chinese and I couldn't figure out a way to change the languge nor find the download button if there is any.
> 
> Can you help me please?

google drive link already updated, please refer to reademe
